### ISSUE TITLE
Noise cleaning in contours

### ISSUE THREAD

**Issue by low-sky** [GBTAmmoniaSurvey/DR1_analysis#14]
For aesthetics, it may be a good idea to clean up the images used in contour maps to kill off the noise spikes.  One way to do this might be binary opening on the parameter maps or on a masked map that is masked at the threshold of the lowest contour.  This just eliminates small regions in the map.

```
from scipy.ndimage import binary_opening
selem = np.array([0,1,0],[1,1,1],[0,1,0])
mask = binary_opening(map > LowestContour,selem)
MaskedMap = mask*map
```

![openingexample](https://cloud.githubusercontent.com/assets/1139910/18019568/fab686c6-6b99-11e6-8735-a8be0172a883.png)

**Comment by rfriesen** [comment]
That's a neat little bit of code, thanks Erik. It works well, but weirdly now my Tkin map plots fail if I include a colorbar with:
ValueError: posx and posy should be finite values
I updated a bunch of python packages so it's more likely related to that, but the colorbar works fine on the other files. Have you come across this before? Also @jpinedaf

**Comment by low-sky** [comment]
Gah!  I think I encountered this as well, but I can't remember what I did to work around it.  I'll try to reproduce it.

**Comment by low-sky** [comment]
Hmmm.  I poked at this and got an unable to reproduce.  Can you point to the full code?

**Comment by rfriesen** [comment]
I think I figured it out - sometimes the colourbar is trying to put text outside the figure (depending on where the ticks are). I'll do some tweaking and upload the hopefully working imaging code.

**Comment by rfriesen** [comment]
So just to clarify, right now I've run this masking to produce images for the paper only, but I can see that it would be useful to perform directly on the parameter map data for release. Thoughts @jpinedaf @low-sky ?

**Comment by low-sky** [comment]
I think it's a legitimate thing to do.  The rationale is that we do not expect significant detections on size scales smaller than the beam, so eliminating isolated pixels is likely culling out noise.
