### ISSUE TITLE
generate figures with integrated intensity maps

### ISSUE THREAD

**Issue by jpinedaf** [GBTAmmoniaSurvey/DR1_analysis#2]
- [x] integrated intensity for all transitions
- [x] plot for all regions

**Comment by rfriesen** [comment]
Do we want to include Herschel contours for these?

**Comment by jpinedaf** [comment]
good question... I don't know. maybe the Herschel 250um or 500um for NH3
(1,1) and for the rest we could show NH3 (1,1) contours on top, what do you
think?

**Comment by rfriesen** [comment]
Yep, I like that.

**Comment by jpinedaf** [comment]
change formatting of axes (via @rfriesen )

``` python
tick_labels.set_style(‘colons’)
tick_labels.set_xformat(‘hh:mm:ss')
tick_labels.set_yformat(‘dd:mm')
```
