### ISSUE TITLE
generate property map figures 

### ISSUE THREAD

**Issue by rfriesen** [GBTAmmoniaSurvey/DR1_analysis#3]
- [x] v_LSR, sigma_v, Tk, Tex, para-N(NH3). Others?
- [x] generate for all regions

**Comment by jpinedaf** [comment]
a lot has been done here. are there any other changes that we should try? 
The latest modification was a change in the color scheme used for V_lsr, and the figures have to be redone (see https://github.com/GBTAmmoniaSurvey/DR1_analysis/commit/64c0fe9405661cda5a6546cb3c577475f1e2a46e)
