### ISSUE TITLE
update and test YSO catalogues

### ISSUE THREAD

**Issue by jpinedaf** [GBTAmmoniaSurvey/DR1_analysis#35]
@rfriesen We need to include the script that is used to generate the images with Herschel data and the footprint of the GAS data, plus the YSO catalogues.

- [x] add script that create figures
- [x] include YSO catalogues (edited if needed)
- [x] check that YSO catalogues are fully plotted
- [ ] Add Herschel data to dataverse
- [x] Add figures to repo

**Comment by rfriesen** [comment]
On it. 
Re: the Herschel data - I'll check with Peter and Ayushi, but I think they didn't want to post their maps publicly yet.

**Comment by jpinedaf** [comment]
We can post just the wavelength and fields used in the figure ;)

**Comment by jpinedaf** [comment]
For B18 the code uses the file rebull_taurus_table7_edit.txt, which is missing. Could you please add it? 
Also, the paper uses a grade system which uses ['A+', 'A', 'A-'] for the reliable sources, at the moment the code is only plotting 'A'... was this on purpose?

**Comment by rfriesen** [comment]
It looks to me like the file is there, in the 'protostars' folder..?
I didn't check for the A+ and A- in the code because none of the newly-detected Class 0/I/flat protostars had those grades, but could add for completeness.

**Comment by jpinedaf** [comment]
you are right! I was checking the folder catalogues instead. No need to modify code before resubmission :)
